#!/usr/bin/env node
/**
 * syncdict.js
 * Generates translator outputs from shared source and the embedded dictionary.
 *
 * Usage:
 *   node syncdict.js          # update index.html and solresol-translator.js
 *   node syncdict.js --check  # exit 1 if generated outputs are stale
 */
'use strict';

const fs = require('fs');
const path = require('path');

const root = __dirname;
const htmlPath = path.join(root, 'index.html');
const libPath = path.join(root, 'solresol-translator.js');
const corePath = path.join(root, 'solresol-core.js');

function read(file) {
  return fs.readFileSync(file, 'utf8');
}

function writeIfChanged(file, next, checkOnly) {
  const current = read(file);
  if (current === next) return false;
  if (!checkOnly) fs.writeFileSync(file, next);
  return true;
}

function extractAfter(source, startMarker, endMarker, label) {
  const start = source.indexOf(startMarker);
  if (start < 0) throw new Error(`could not locate ${label} start marker`);
  const bodyStart = start + startMarker.length;
  const end = source.indexOf(endMarker, bodyStart);
  if (end < 0) throw new Error(`could not locate ${label} end marker`);
  return {
    value: source.slice(bodyStart, end),
    start,
    bodyStart,
    end,
    endAfter: end + endMarker.length,
  };
}

function extractDictFromHtml(html) {
  const marker = 'const SOLRESOL_DICT = ';
  const found = extractAfter(html, marker, ';\n', 'SOLRESOL_DICT');
  try {
    JSON.parse(found.value);
  } catch (e) {
    throw new Error(`SOLRESOL_DICT in index.html is not valid JSON: ${e.message}`);
  }
  return found.value;
}

function embeddedCoreExpression(coreSource) {
  return `(() => {\n  const module = { exports: {} };\n  const exports = module.exports;\n${coreSource.split('\n').map(line => `  ${line}`).join('\n')}\n  return module.exports;\n})()`;
}

function browserBlock(coreSource) {
  return `// <solresol-translator-core generated by syncdict.js>\nconst SOLRESOL_TRANSLATOR_CORE = ${embeddedCoreExpression(coreSource)};\nconst SolresolTranslator = SOLRESOL_TRANSLATOR_CORE.createTranslator(SOLRESOL_DICT);\n// </solresol-translator-core>\n`;
}

function replaceBrowserBlock(html, coreSource) {
  const block = browserBlock(coreSource);
  const startMarker = '// <solresol-translator-core generated by syncdict.js>\n';
  const endMarker = '// </solresol-translator-core>\n';
  if (html.includes(startMarker)) {
    const found = extractAfter(html, startMarker, endMarker, 'browser translator core');
    return html.slice(0, found.start) + block + html.slice(found.endAfter);
  }

  const anchor = '// SOLRESOL_DICT is injected above as a const from the embedded JSON.\n';
  const idx = html.indexOf(anchor);
  if (idx < 0) throw new Error('could not locate dictionary comment in index.html');
  return html.slice(0, idx + anchor.length) + block + '\n' + html.slice(idx + anchor.length);
}

function replaceFunction(source, name, replacement, fromIndex = 0) {
  const start = source.indexOf(`function ${name}(`, fromIndex);
  if (start < 0) throw new Error(`could not locate function ${name} in index.html`);
  const open = source.indexOf('{', start);
  if (open < 0) throw new Error(`could not locate function ${name} body in index.html`);
  let depth = 0;
  for (let i = open; i < source.length; i++) {
    const ch = source[i];
    if (ch === '{') depth++;
    if (ch === '}') depth--;
    if (depth === 0) {
      return source.slice(0, start) + replacement + source.slice(i + 1);
    }
  }
  throw new Error(`could not locate function ${name} end in index.html`);
}

function updateIndex(html, coreSource) {
  let next = replaceBrowserBlock(html, coreSource);
  const generatedEnd = next.indexOf('// </solresol-translator-core>\n');
  if (generatedEnd < 0) throw new Error('could not locate generated translator core in index.html');
  const appStart = generatedEnd + '// </solresol-translator-core>\n'.length;
  next = replaceFunction(next, 'splitSol', 'function splitSol(key) {\n  return SolresolTranslator.splitSol(key);\n}', appStart);
  next = replaceFunction(next, 'translate', 'function translate(text) {\n  return SolresolTranslator.ToSolReSol(text);\n}', appStart);
  return next;
}

function standaloneLibrary(dictJson, coreSource) {
  return `/**\n * solresol-translator.js\n * Standalone English <-> Solresol translation library.\n *\n * Generated by syncdict.js from solresol-core.js and the dictionary embedded in index.html.\n *\n * API:\n *   ToSolReSol(text)    -- English string -> array of word objects\n *   FromSolReSol(text)  -- space-separated Solresol keys -> English candidates\n *   splitSol(key)       -- split a concatenated Solresol key into syllable array\n *\n * Works as a CommonJS module, AMD module, ES module default export, or browser global\n * (SolresolTranslator).\n *\n * IETF: art-x-solresol | ISO 639-3: qso\n */\n(function(root, factory) {\n  if (typeof module !== 'undefined' && module.exports) {\n    module.exports = factory();\n  } else if (typeof define === 'function' && define.amd) {\n    define([], factory);\n  } else {\n    root.SolresolTranslator = factory();\n  }\n}(typeof globalThis !== 'undefined' ? globalThis : this, function() {\n'use strict';\n\nconst CORE = ${embeddedCoreExpression(coreSource)};\nconst DICT = ${dictJson};\n\nreturn CORE.createTranslator(DICT);\n\n}));\n`;
}

function sync(options = {}) {
  const checkOnly = !!options.checkOnly;
  const html = read(htmlPath);
  const coreSource = read(corePath);
  const dictJson = extractDictFromHtml(html);
  JSON.parse(dictJson);

  const nextHtml = updateIndex(html, coreSource);
  const nextLib = standaloneLibrary(dictJson, coreSource);

  const stale = [];
  if (writeIfChanged(htmlPath, nextHtml, checkOnly)) stale.push('index.html');
  if (writeIfChanged(libPath, nextLib, checkOnly)) stale.push('solresol-translator.js');

  const count = Object.keys(JSON.parse(dictJson)).length;
  if (stale.length && checkOnly) {
    const message = `syncdict: OUT OF SYNC (${stale.join(', ')}) - run "node syncdict.js" to update generated files.`;
    if (options.throwOnStale) throw new Error(message);
    return { stale, count, message, ok: false };
  }
  const message = stale.length
    ? `syncdict: updated ${stale.join(', ')} (${count} dictionary entries).`
    : `syncdict: already in sync (${count} dictionary entries).`;
  return { stale, count, message, ok: stale.length === 0 || !checkOnly };
}

function main() {
  const result = sync({ checkOnly: process.argv.includes('--check') });
  if (!result.ok) {
    console.error(result.message);
    process.exit(1);
  }
  console.log(result.message);
}

if (require.main === module) {
  try {
    main();
  } catch (e) {
    console.error(`syncdict: ${e.message}`);
    process.exit(1);
  }
}

module.exports = {
  sync,
  extractDictFromHtml,
  updateIndex,
  standaloneLibrary,
};
